export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FALIURE: "LOGIN_FALIURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FALIURE: "LOGOUT_FALIURE",
};

export const userConstant = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FALIURE: "USER_REGISTER_FALIURE",
};

export const quesConstant = {
  FETCH_QUES_REQUEST: "FETCH_QUES_REQUEST",
  FETCH_QUES_SUCCESS: "FETCH_QUES_SUCCESS",
  FETCH_QUES_FALIURE: "FETCH_QUES_FALIURE"
};

export const notifyConstant={
  NOTIFY_SUCCESS:"NOTIFY_SUCCESS",
  NOTIFY_REQUEST:'NOTIFY_REQUEST',
  NOTIFY_ERROR:"NOTIFY_ERROR"
}
export const fileConstant={
  FILE_REQUEST:'FILE_REQUEST',
  FILE_SUCCESS:'FILE_SUCCESS',
  FILE_FALIURE:'FILE_FALIURE'
}